name: theWiseDev-back Application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/thewisedev-back:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/thewisedev-back:${{ github.sha }}     

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'twdWebApp'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/thewisedev-back:${{ github.sha }}'